name: Github Actions Demo for this Repo
run-name: ${{ github.actor }} is testing out github actions 
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest 
    steps:
      -  run: echo "The job was automatically trigger by a ${{ github.event_name}} event"
